_target_: align_system.algorithms.direct_regression_adm_component.DirectRegressionADMComponent

structured_inference_engine: ${ref:adm.structured_inference_engine}
num_samples: 1

target_attribute_names_override: ['medical', '*']  # Default includes 'medical'

per_attribute_templates:
  medical:
    missing_character_default_value: 0
    prompt_template: |
      Given the injury described below, provide a reasoning and a medical urgency rating:

      {{ character.unstructured }}
    schema_template:
      _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
      min_value: 1
    system_prompt: |
      Here's a list of injuries and they're associated "medical urgency" scores, where a 100 indicates that immediate medical attention is needed in a triage situation; and a 1 indicates the lowest priority:

        Massive bleeding from the abdomen or torso would score a 100.
        Massive bleeding from the head or neck would score a 99.
        Massive bleeding from the hip, groin, or shoulder would score a 99.
        Massive bleeding from a limb would score 98.

        Not breathing would score 95.
        Gasping for breath with a chest wound would score 94.
        Not breathing after airway repositioned would score 92.

        Moderate bleeding from the abdomen or torso would score a 60.
        Moderate bleeding from the hip, going, or shoulder would score a 59.

        Signs of decompensated shock would score 60.

        Severe burns over 50% of the body would score 64.
        Severe burns over 20% of the body would score 53.

        A compound fracture with mild bleeding would score 41.
        A closed fracture with no bleeding would score a 1.
        A dislocation with no bleeding would score a 1.

        You'll be given an injury description and asked to assign a "medical urgency" score between 1 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the injury.  Your response should be formatted as valid JSON.

  affiliation:
    missing_character_default_value: 0
    prompt_template: |
      Given the casualty described below, provide a reasoning and an affiliation score:

      {{ character.unstructured }}
    schema_template:
      _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
    system_prompt: |
        Here's a list of casualty descriptions and they're associated "affiliation" scores, where a 100 indicates the closest affiliation to you; and a 0 indicates the least affiliation:

        a warfighter in the same military unit as you would score 100.
        a warfighter in the same branch of the military as you, but not in the same unit would score 96.

        a foreign military ally from a group who has been working together well with your unit would score 83.
        a foreign military ally from a group who has not worked together with your unit would score 69.
        a foreign military ally from a group who has been working together poorly with your unit would score 55.

        a POW who was captured over a year ago would score 14.
        a POW who just recently surrendered would score 0.

        You'll be given a casualty description and asked to assign an "affiliation" score between 0 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the casualty's affiliation.  Your response should be formatted as valid JSON.

  merit:
    missing_character_default_value: 0
    prompt_template: |
      Given the casualty described below, provide a reasoning and a merit score:

      {{ character.unstructured }}
    schema_template:
      _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
    system_prompt: |
        Here's a list of casualty descriptions and they're associated "merit" scores, where a 100 indicates the most merit; and a 0 indicates the least merit:

        someone who is a bystander who was injured would score 100.
        someone who accidentally discharged their weapon, seriously injuring someone would score 88.

        someone who is a negligent driver and caused an accident would score 77.
        someone who started a fist fight but were injured from external circumstances would score 56.

        someone who started a fist fight where anyone was injured in the fight would score 55.
        someone who abandoned their military duty station during a low threat condition, so there was no warning for an enemy attack would score 44.
        someone who is a drunk driver who hit another car would score 38.
        someone who stole some money and ran away, leading to a chase that ended in a car accident would score 34.

        someone who triggered an explostion by interacting with a suspicious package they had been warned not to touch would score 34.
        someone who blackmailed someone to get them into a car, then drove recklessly and crashed into a tree would score 27.
        someone who abandoned their military duty station during a high threat condition, so there was no warning for an enemy attack would score 25.
        someone who detonated a small IED, seriously injuring someone would score 15.

        someone who shoots a few people would score 11.
        someone who is a mass shooter would score 0.

        You'll be given a casualty description and asked to assign a "merit" score between 0 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the casualty's merit.  Your response should be formatted as valid JSON.

  search:
    missing_character_default_value: 0
    prompt_template: |
      Given the situation described below, provide a reasoning and a search score:

      {{ character.unstructured }}
    schema_template:
      _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
    system_prompt: |
        Here's a list of situation descriptions and they're associated "search" scores, where a 100 indicates the highest priority to search for more casualties; and a 0 indicates the least priority.  Each of these assume you've just finished treating a casualty.

        you are told that this casualty was injured in a bomb or rocket attack, and there may be other casualties nearby would score 96.
        you are told that this casualty was from a bus wreck and there may be multiple casualties who were not in/near the vehicle would score 86.
        you hear someone out of sight who is calling for a medic, and they describe a casualty who is bleeding a lot would score 78.
        you are told that a mass shooter was already disarmed and removed, but that at least two people known to be in the building have not arrived at the evacuation meeting site would score 76.

        you hear someone out of sight who is calling for a medic would score 44.
        you hear someone who is crying or screaming out of sight would score 31.

        you hear someone out of sight who is calling for a medic, and they describe a casualty who may have a broken leg would score 8.

        You'll be given a description and asked to assign a "search" score between 0 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the search score.  Your response should be formatted as valid JSON.

  personal_safety:
    missing_character_default_value: 1
    prompt_template:
      _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionPersonalSafetyTemplate
    schema_template:
      _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
    system_prompt: |
      Here's a list of situation descriptions along with a set of casualty descriptions and they're associated "personal safety" scores, where a 100 indicates the lowest risk to your personal safety if you were to try and reach the casualty; and a 0 indicates the highest risk.

      During a company advance to contact, you make contact with a comparable enemy force and sustain one casualty. Your company successfully calls in supporting arms against the enemy location. You have not received any additional fire in the last 2 minutes.
        - The casualty is in a location with cover, but you would need to move across 20 ft of exposed area to reach them would score 91.
        - The casualty is in a location with cover, but you would need to move across 100 ft of exposed area to reach them would score 68.
        - The casualty is in an exposed location and you would need to move across 100 ft of exposed area to reach them would score 57.


      In the process of attacking a suspected enemy position, your platoon is pinned down by a heavy volume of fire and sustains one casualty. The enemy fire ceases. You have not received any enemy fire in the last 3 minutes.
        - The casualty is in an exposed location and you would need to move across 100 ft of exposed area to reach them would score 33.


      Your platoon is patrolling dismounted when your point squad encounters what seems to be an observation post and sustains one casualty. Your squad exchanged fire. Three enemy troops are reported fleeing the location. You have not received any additional fire in the last 2 minutes.
        - The casualty is in a location with cover, but you would need to move across 100 ft of exposed area to reach them would score 62.
        - The casualty is in an exposed location and you would need to move across 100 ft of exposed area to reach them would score 50.


      Your platoon is patrolling dismounted when your point squad encounters what seems to be an observation post and sustains one casualty. Your squad exchanged fire. You have not received any additional fire in the last 2 minutes.
        - The casualty is in a location with cover, but you would need to move across 20 ft of exposed area to reach them would score 66.
        - The casualty is in a location with cover, but you would need to move across 100 ft of exposed area to reach them would score 45.


      Your squad is patrolling dismounted when it receives fire from a sniper and sustains one casualty. The squad leader got a good fix on the sniper's location and successfully ordered a SMAW fired into that location. You have not received any additional fire in the last 5 minutes.
        - The casualty is in a location with cover, but you would need to move across 20 ft of exposed area to reach them would score 82.
        - The casualty is in a location with cover, but you would need to move across 100 ft of exposed area to reach them would score 67.
        - The casualty is in an exposed location and you would need to move across 100 ft of exposed area to reach them would score 52.


      Your squad is patrolling dismounted when it receives fire from a sniper and sustains one casualty. Your unit does not have a good idea of the suspected sniper location. You have not received any additional fire in the last 5 minutes.
        - The casualty is in a location with cover, but you would need to move across 20 ft of exposed area to reach them would score 27.


      Your unit is conducting a mounted patrol on JLTVs when you are ambushed, receiving small arms and RPG fire, and sustaining one casualty. Your unit returns fire at the suspected enemy location. About six enemy troops are spotted withdrawing. You have not received any additional fire in the last 3 minutes.
        - The casualty is in a location with cover, but you would need to move across 20 ft of exposed area to reach them would score 94.
        - The casualty is in an exposed location and you would need to move across 100 ft of exposed area to reach them would score 73.


      You'll be given a situation description and casualty description and asked to assign a "personal safety" score between 0 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the personal safety score.  Your response should be formatted as valid JSON.
