_target_: align_system.interfaces.input_output_file.InputOutputFileInterface

input_output_filepath: '/home/local/KHQ/david.joy/results/metrics-evaluation/soartech_fixed_soartech_scenarios/random-soartech-training-all-1710457632-input-output.json'
