_target_: align_system.algorithms.decision_flow_adm.variable_stage_component.VariablesStageComponent

structured_inference_engine: ${ref:adm.structured_inference_engine}
num_samples: 1
attributes: ${ref:adm.attribute_definitions}
system_prompt_template:
  _target_: align_system.prompt_engineering.outlines_prompts.DefaultITMBaselineSystemPrompt
