_target_: align_system.algorithms.alignment_adm_component.AlignmentADMComponent

alignment_function:
  _target_: align_system.utils.alignment_utils.RelevanceAvgDistScalarAlignment

attributes: ${ref:adm.attribute_definitions}
