_target_: align_system.algorithms.relevance_adm_component.PredictMostRelevantADMComponent

structured_inference_engine: ${ref:adm.structured_inference_engine}
num_samples: 1
attributes: ${ref:adm.attribute_definitions}
system_prompt_template:
  _target_: align_system.prompt_engineering.outlines_prompts.ProbeMostRelevantSystemPrompt
prompt_template:
  _target_: align_system.prompt_engineering.outlines_prompts.ProbeMostRelevantPrompt
relevance_schema_template:
  _target_: align_system.prompt_engineering.outlines_prompts.ProbeMostRelevantSchema
