_target_: align_system.interfaces.ai2thor_interface.AI2ThorInterface

scene: FloorPlan1
prompts: [0]        # 0=apple, 1=tomato, 2=red fruit
save_frames: false
frame_dir: frames
starting_point: default
