_target_: align_system.data_models.compat.ta3_ph1_client_models.AlignmentTarget
id: EDUCATION_College_graduate_some_postgrad_high
kdma_values:
- kdma: EDUCATION_College graduate/some postgrad
  value: 1.0
