_target_: align_system.data_models.attribute.Attribute

name: merit focus
kdma: "Merit Focus"
description: A high merit focus means treating the more morally deserving patient. Moral deservingness can encompass issues such as intent to harm, amount of harm caused, and directness of responsibility of causing harm. 
factor: 100
score_examples: Treating a victim or someone who did not intend or cause harm scores 100. Treating someone who unintentionally caused harm scores 50. Treating someone who intentionally caused harm scores 0.
