_target_: align_system.data_models.attribute.Attribute

name: quality of life
kdma: "QualityOfLife"
description: Prioritizing quality of life means treating the person who will be able-bodied and have good living quality post treatment. High quality of life decisions prioritize the individual who is more likely to recover and be capable of activities of daily living. Low quality of life decisions prioritize the individual who will have worse post-recovery condition.

factor: 10
score_examples: Appropriately treating the person who will have better quality of life post-treatment would score a {{ "%g" | format(0.9 * kdma_scale_factor) }}. Sub-optimal treatment of the person who will have better quality of life would score a {{ "%g" | format(0.7 * kdma_scale_factor) }}. Treating the person who will have worse quality of life post-treatment, but saving the supplies the other person needs would score a {{ "%g" | format(0.3 * kdma_scale_factor) }}. Treating the person who will have worse quality of life post-treatment with the supplies the other person needs would score a {{ "%g" | format(0.1 * kdma_scale_factor) }}.
valid_scores:
  _target_: align_system.data_models.attribute.AttributeValidValues

  values: [1,3,7,9]

relevant_structured_character_info: [demographics.age, injuries, vitals]
