name: action_based

defaults:
  - _self_
  - interface: input_output_file
  - adm: outlines_transformers_structured_baseline
  - override hydra/job_logging: custom

loglevel: "EXPLAIN"

save_log: true
save_raw_log: true
save_input_output: true
save_scoring_output: true
save_alignment_targets: false
save_timing: true
save_last_unstructured_state_per_scenario: false

align_to_target: false
