_target_: align_system.data_models.compat.ta3_ph1_client_models.AlignmentTarget
id: qol-prelim-emt-d29ef563
kdma_values:
- kdes:
    globalnorm:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsKSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDUAAAAAAAAPA/

        AAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/AAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A

        AAAAAADwPwAAAAAAAPA/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwqFlGgnjAJpOJSJiIeUUpQoSwNo

        K05OTkr/////Sv////9LAHSUYolDUAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAA

        AAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAAlHSUYmgdaCBLAIWU

        aCKHlFKUKEsBSwGFlGgnjANWMzKUiYiHlFKUKEsDjAF8lE4ojAlpZHhfc3RhcnSUjAdpZHhfZW5k

        lIwHaXNfbGVhZpSMBnJhZGl1c5R0lH2UKGhBaCeMAmk4lImIh5RSlChLA2grTk5OSv////9K////

        /0sAdJRiSwCGlGhCaElLCIaUaENoSUsQhpRoRGgqSxiGlHVLIEsBSxB0lGKJQyAAAAAAAAAAAAoA

        AAAAAAAAAQAAAAAAAAAAAAAAAADgP5R0lGJoHWggSwCFlGgih5RSlChLAUsCSwFLAYeUaCqJQxAA

        AAAAAAAAAAAAAAAAAPA/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: globalnorm
    globalnormx_localnormy:
      kde: 'gASVxAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwKMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsKSwKGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDoAAAAAAAAPA/

        AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A

        AAAAAAAAAAAAAAAAAAAAAAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAA

        AAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D+UdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLCoWUaCeMAmk4lImIh5RSlChLA2grTk5OSv////9K/////0sAdJRiiUNQAAAAAAAAAAABAAAA

        AAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAgAAAAA

        AAAACQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyU

        TiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiU

        iYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaU

        dUsgSwFLEHSUYolDIAAAAAAAAAAACgAAAAAAAAABAAAAAAAAAM07f2aeoOY/lHSUYmgdaCBLAIWU

        aCKHlFKUKEsBSwJLAUsCh5RoKolDIAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/lHSU

        YksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3RfbWV0cmljc5RoFZOUaFiME0V1

        Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCqJ

        QwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgqiUMIAAAAAAAAAACUdJRih5Ri

        TnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: globalnormx_localnormy
    localnorm:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsKSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDUAAAAAAAAPA/

        AAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/AAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A

        AAAAAADwPwAAAAAAAPA/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwqFlGgnjAJpOJSJiIeUUpQoSwNo

        K05OTkr/////Sv////9LAHSUYolDUAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAA

        AAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAAlHSUYmgdaCBLAIWU

        aCKHlFKUKEsBSwGFlGgnjANWMzKUiYiHlFKUKEsDjAF8lE4ojAlpZHhfc3RhcnSUjAdpZHhfZW5k

        lIwHaXNfbGVhZpSMBnJhZGl1c5R0lH2UKGhBaCeMAmk4lImIh5RSlChLA2grTk5OSv////9K////

        /0sAdJRiSwCGlGhCaElLCIaUaENoSUsQhpRoRGgqSxiGlHVLIEsBSxB0lGKJQyAAAAAAAAAAAAoA

        AAAAAAAAAQAAAAAAAAAAAAAAAADgP5R0lGJoHWggSwCFlGgih5RSlChLAUsCSwFLAYeUaCqJQxAA

        AAAAAAAAAAAAAAAAAPA/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: localnorm
    rawscores:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsKSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDUM3MzMzMzOw/

        mpmZmZmZuT/NzMzMzMzsP83MzMzMzOw/mpmZmZmZuT/NzMzMzMzsP83MzMzMzOw/zczMzMzM7D/N

        zMzMzMzsP83MzMzMzOw/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwqFlGgnjAJpOJSJiIeUUpQoSwNo

        K05OTkr/////Sv////9LAHSUYolDUAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAA

        AAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAAlHSUYmgdaCBLAIWU

        aCKHlFKUKEsBSwGFlGgnjANWMzKUiYiHlFKUKEsDjAF8lE4ojAlpZHhfc3RhcnSUjAdpZHhfZW5k

        lIwHaXNfbGVhZpSMBnJhZGl1c5R0lH2UKGhBaCeMAmk4lImIh5RSlChLA2grTk5OSv////9K////

        /0sAdJRiSwCGlGhCaElLCIaUaENoSUsQhpRoRGgqSxiGlHVLIEsBSxB0lGKJQyAAAAAAAAAAAAoA

        AAAAAAAAAQAAAAAAAACamZmZmZnZP5R0lGJoHWggSwCFlGgih5RSlChLAUsCSwFLAYeUaCqJQxCa

        mZmZmZm5P83MzMzMzOw/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: rawscores
  kdma: QualityOfLife
