_target_: swagger_client.models.AlignmentTarget
id: QOL_EMT_a1304ca3a9e8
kdma_values:
- kdes:
    globalnorm:
      kde: 'gASVdAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsLSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDWAAAAAAAAAAA

        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D/////////nPwAAAAAAAAAAAAAAAAAA8D8A

        AAAAAAAAAAAAAAAAAAAAAAAAAAAA8D+UdJRiaB1oIEsAhZRoIoeUUpQoSwFLC4WUaCeMAmk4lImI

        h5RSlChLA2grTk5OSv////9K/////0sAdJRiiUNYAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAA

        AAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAgAAAAAAAAACQAAAAAAAAAKAAAA

        AAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBhZRoJ4wDVjMylImIh5RSlChLA4wBfJROKIwJaWR4

        X3N0YXJ0lIwHaWR4X2VuZJSMB2lzX2xlYWaUjAZyYWRpdXOUdJR9lChoQWgnjAJpOJSJiIeUUpQo

        SwNoK05OTkr/////Sv////9LAHSUYksAhpRoQmhJSwiGlGhDaElLEIaUaERoKksYhpR1SyBLAUsQ

        dJRiiUMgAAAAAAAAAAALAAAAAAAAAAEAAAAAAAAAAAAAAAAA4D+UdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAksBSwGHlGgqiUMQAAAAAAAAAAAAAAAAAADwP5R0lGJLKEsBSwFLAEsASwBLAIwdc2tsZWFy

        bi5tZXRyaWNzLl9kaXN0X21ldHJpY3OUaBWTlGhYjBNFdWNsaWRlYW5EaXN0YW5jZTY0lJOUhZRS

        lEdAAAAAAAAAAGgdaCBLAIWUaCKHlFKUKEsBSwGFlGgqiUMIAAAAAAAAAACUdJRiaB1oIEsAhZRo

        IoeUUpQoSwFLAUsBhpRoKolDCAAAAAAAAAAAlHSUYoeUYk50lGKMEF9za2xlYXJuX3ZlcnNpb26U

        jAUxLjUuMZR1Yi4=

        '
      label: globalnorm
    globalnormx_localnormy:
      kde: 'gASV3AQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwKMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsLSwKGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDsAAAAAAAAAAA

        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D8A

        AAAAAADwPwAAAAAAAPA/////////5z/////////nPwAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAA

        AAAAAPA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/lHSU

        YmgdaCBLAIWUaCKHlFKUKEsBSwuFlGgnjAJpOJSJiIeUUpQoSwNoK05OTkr/////Sv////9LAHSU

        YolDWAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAAAAAAAAAFAAAAAAAAAAYAAAAA

        AAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAACgAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFL

        AYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFm

        lIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaU

        aEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAACwAAAAAAAAABAAAA

        AAAAAM07f2aeoOY/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsCh5RoKolDIAAAAAAAAAAAAAAA

        AAAAAAAAAAAAAADwPwAAAAAAAPA/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3Mu

        X2Rpc3RfbWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAA

        aB1oIEsAhZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsB

        SwGGlGgqiUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHVi

        Lg==

        '
      label: globalnormx_localnormy
    localnorm:
      kde: 'gASVdAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsLSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDWAAAAAAAAAAA

        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D/////////nPwAAAAAAAAAAAAAAAAAA8D8A

        AAAAAAAAAAAAAAAAAAAAAAAAAAAA8D+UdJRiaB1oIEsAhZRoIoeUUpQoSwFLC4WUaCeMAmk4lImI

        h5RSlChLA2grTk5OSv////9K/////0sAdJRiiUNYAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAA

        AAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAgAAAAAAAAACQAAAAAAAAAKAAAA

        AAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBhZRoJ4wDVjMylImIh5RSlChLA4wBfJROKIwJaWR4

        X3N0YXJ0lIwHaWR4X2VuZJSMB2lzX2xlYWaUjAZyYWRpdXOUdJR9lChoQWgnjAJpOJSJiIeUUpQo

        SwNoK05OTkr/////Sv////9LAHSUYksAhpRoQmhJSwiGlGhDaElLEIaUaERoKksYhpR1SyBLAUsQ

        dJRiiUMgAAAAAAAAAAALAAAAAAAAAAEAAAAAAAAAAAAAAAAA4D+UdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAksBSwGHlGgqiUMQAAAAAAAAAAAAAAAAAADwP5R0lGJLKEsBSwFLAEsASwBLAIwdc2tsZWFy

        bi5tZXRyaWNzLl9kaXN0X21ldHJpY3OUaBWTlGhYjBNFdWNsaWRlYW5EaXN0YW5jZTY0lJOUhZRS

        lEdAAAAAAAAAAGgdaCBLAIWUaCKHlFKUKEsBSwGFlGgqiUMIAAAAAAAAAACUdJRiaB1oIEsAhZRo

        IoeUUpQoSwFLAUsBhpRoKolDCAAAAAAAAAAAlHSUYoeUYk50lGKMEF9za2xlYXJuX3ZlcnNpb26U

        jAUxLjUuMZR1Yi4=

        '
      label: localnorm
    rawscores:
      kde: 'gASVdAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsLSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDWJqZmZmZmbk/

        mpmZmZmZuT+amZmZmZm5P83MzMzMzOw/zczMzMzM7D9mZmZmZmbmP5qZmZmZmbk/zczMzMzM7D+a

        mZmZmZm5P5qZmZmZmbk/zczMzMzM7D+UdJRiaB1oIEsAhZRoIoeUUpQoSwFLC4WUaCeMAmk4lImI

        h5RSlChLA2grTk5OSv////9K/////0sAdJRiiUNYAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAA

        AAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAgAAAAAAAAACQAAAAAAAAAKAAAA

        AAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBhZRoJ4wDVjMylImIh5RSlChLA4wBfJROKIwJaWR4

        X3N0YXJ0lIwHaWR4X2VuZJSMB2lzX2xlYWaUjAZyYWRpdXOUdJR9lChoQWgnjAJpOJSJiIeUUpQo

        SwNoK05OTkr/////Sv////9LAHSUYksAhpRoQmhJSwiGlGhDaElLEIaUaERoKksYhpR1SyBLAUsQ

        dJRiiUMgAAAAAAAAAAALAAAAAAAAAAEAAAAAAAAAmpmZmZmZ2T+UdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAksBSwGHlGgqiUMQmpmZmZmZuT/NzMzMzMzsP5R0lGJLKEsBSwFLAEsASwBLAIwdc2tsZWFy

        bi5tZXRyaWNzLl9kaXN0X21ldHJpY3OUaBWTlGhYjBNFdWNsaWRlYW5EaXN0YW5jZTY0lJOUhZRS

        lEdAAAAAAAAAAGgdaCBLAIWUaCKHlFKUKEsBSwGFlGgqiUMIAAAAAAAAAACUdJRiaB1oIEsAhZRo

        IoeUUpQoSwFLAUsBhpRoKolDCAAAAAAAAAAAlHSUYoeUYk50lGKMEF9za2xlYXJuX3ZlcnNpb26U

        jAUxLjUuMZR1Yi4=

        '
      label: rawscores
  kdma: QualityOfLife
