_target_: swagger_client.models.AlignmentTarget
id: vol-human-5032922-SplitLowMulti-ph1
kdma_values:
- kdes:
    globalnorm:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMAAAAAAAAAAA

        ////////zz8AAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAAAAAAAAAOA/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEAAAAAAAAAAA

        AAAAAAAA8D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: globalnorm
    globalnormx_localnormy:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwKMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwKGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDYAAAAAAAAAAA

        AAAAAAAAAAD////////PP////////88/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D8A

        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsGhZRo

        J4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEAAAAAAAAAAgAA

        AAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeM

        A1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFk

        aXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsI

        hpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAABAAAAAAAAAM07

        f2aeoOY/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsCh5RoKolDIAAAAAAAAAAAAAAAAAAAAAAA

        AAAAAADwPwAAAAAAAPA/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: globalnormx_localnormy
    localnorm:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMAAAAAAAAAAA

        ////////zz8AAAAAAAAAAAAAAAAAAPA/AAAAAAAAAAAAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAAAAAAAAAOA/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEAAAAAAAAAAA

        AAAAAAAA8D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: localnorm
    rawscores:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMJqZmZmZmbk/

        MzMzMzMz0z+amZmZmZm5P83MzMzMzOw/mpmZmZmZuT+amZmZmZm5P5R0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAJqZmZmZmdk/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEJqZmZmZmbk/

        zczMzMzM7D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: rawscores
  kdma: PerceivedQuantityOfLivesSaved
  scores:
  - 0.1
  - 0.3
  - 0.1
  - 0.9
  - 0.1
  - 0.1
