defaults:
  - outlines_regression_aligned_comparative

inference_kwargs:
  generator_batch_size: 5
  incontext:
    number: 5
    method: prompt_bert_similarity
    leave_one_out: false
    normalization: null
    sort_actions: true
    datasets:
      QualityOfLife: /data/shared/samba/phase1_icl/qol_train1_20241105.json
      PerceivedQuantityOfLivesSaved: /data/shared/samba/phase1_icl/vol_train1_20241105.json
