instance:
  _target_: align_system.algorithms.hybrid_kaleido_adm.HybridKaleidoADM

  kaleido_init_kwargs:
    model_name: 'allenai/kaleido-large'
    use_tqdm: False

  llm_init_kwargs:
    hf_model: 'meta-llama/Llama-2-7b-chat-hf'
    precision: 'half'

inference_kwargs:
  # Kaleido kwargs
  distance_fn: 'RelevanceWeightedDistance'
  kdma_descriptions_map: 'align_system/algorithms/lib/templates/kdma_descriptions_short_metrics_eval.yml'
    # LLM kwargs
  answer_attempts: 5
