instance:
  _target_: align_system.algorithms.llama_2_multi_kdma_adm.Llama2MultiKDMAADM

  hf_model: meta-llama/Llama-2-13b-chat-hf
  precision: half
  temperature: 0.7

inference_kwargs:
  predict_outcomes: true
  max_new_tokens: 512
