_target_: align_system.algorithms.icl_adm_component.ICLADMComponent

icl_generator:
  _target_: align_system.utils.incontext_utils.RelevanceIncontextExampleGenerator
  incontext_settings:
    number: 2
    method: prompt_bert_similarity
    leave_one_out_strategy: null
    normalization: null
    sort_actions: true
    most_similar_first: false
    datasets:
      QualityOfLife: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/phase1_icl}/qol_all_20241217.json
      PerceivedQuantityOfLivesSaved: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/phase1_icl}/vol_all_20241217.json
      Moral judgement: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/phase1_icl}/moral_judgement_20241106.json
      Ingroup Bias: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/phase1_icl}/ingroup_bias_20241106_no_IO2.json
