_target_: align_system.algorithms.icl_adm_component.ICLADMComponent

target_attribute_names_override: ['medical', '*']

icl_generator_partial:
  _target_: align_system.utils.incontext_utils.Phase2ComparativeRegressionIncontextExampleGenerator
  # Partially initialize so we can finish initialization with multiple
  # alignment targets
  _partial_: true

  incontext_settings:
    number: 5
    method: prompt_bert_similarity
    leave_one_out_strategy: null
    normalization: null
    sort_actions: true
    most_similar_first: false
    datasets:
      medical: ${oc.env:ICL_DATABASE_DIR,align_system/resources/icl/phase2}/medical.json
      affiliation: ${oc.env:ICL_DATABASE_DIR,align_system/resources/icl/phase2}/affiliation.json
      merit: ${oc.env:ICL_DATABASE_DIR,align_system/resources/icl/phase2}/merit.json
      personal_safety: ${oc.env:ICL_DATABASE_DIR,align_system/resources/icl/phase2}/personal_safety.json
      search: ${oc.env:ICL_DATABASE_DIR,align_system/resources/icl/phase2}/search.json

  state_hydration_domain: p2triage
