_target_: align_system.algorithms.icl_adm_component.PromptBasedICLADMComponent

icl_generator_partial:
  _target_: align_system.utils.incontext_utils.BaselineIncontextExampleGenerator
  # Partially initialize so we can finish initialization with multiple
  # alignment targets
  _partial_: true

  incontext_settings:
    number: 5
    method: scenario_bert_similarity
    leave_one_out_strategy: null
    normalization: null
    sort_actions: true
    most_similar_first: false
    datasets:
      MoralDesert: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/integrated_results_metrics_eval/captured_dataset_for_chris}/baseline_adept_high-1715105775-input-output.json
      maximization: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/integrated_results_metrics_eval/captured_dataset_for_chris}/baseline_soartech_high-1716581856-input-output.json
      Moral judgement: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/dry_run}/moral_judgement_20240826.json
      Ingroup Bias: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/dry_run}/ingroup_bias_20240826.json
      QualityOfLife: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/dry_run}/qol_20240826.json
      PerceivedQuantityOfLivesSaved: ${oc.env:ICL_DATABASE_DIR,/data/shared/samba/dry_run}/vol_20240826.json
