_target_: align_system.algorithms.icl_adm_component.ICLADMComponent

icl_generator_partial:
  _target_: align_system.utils.incontext_utils.ComparativeRegressionIncontextExampleGenerator
  # Partially initialize so we can finish initialization with multiple
  # alignment targets
  _partial_: true

  incontext_settings:
    number: 5
    method: prompt_bert_similarity
    leave_one_out_strategy: null
    normalization: null
    sort_actions: true
    most_similar_first: false
    datasets:
      QualityOfLife: align_system/resources/icl/phase1/qol_all_20241217.json
      PerceivedQuantityOfLivesSaved: align_system/resources/icl/phase1/vol_all_20241217.json
      Moral judgement: align_system/resources/icl/phase1/moral_judgement_20241106.json
      Ingroup Bias: align_system/resources/icl/phase1/ingroup_bias_20241106_no_IO2.json
