_target_: align_system.algorithms.icl_adm_component.PromptBasedICLADMComponent

icl_generator_partial:
  _target_: align_system.utils.incontext_utils.BaselineIncontextExampleGenerator
  # Partially initialize so we can finish initialization with multiple
  # alignment targets
  _partial_: true

  incontext_settings:
    number: 10
    method: prompt_bert_similarity
    leave_one_out_strategy: scenario_description
    normalization: null
    sort_actions: false
    most_similar_first: false
    datasets:
      START: align_system/resources/icl/tagging/train3.json
      SALT: align_system/resources/icl/tagging/train3.json
      BCD_SIEVE: align_system/resources/icl/tagging/train3.json

  state_hydration_domain: minimal
