_target_: align_system.algorithms.open_world_components.OWActionParameterCompletionADMComponent

structured_inference_engine: ${ref:adm.structured_inference_engine}

system_prompt:
  _target_: align_system.prompt_engineering.outlines_prompts.DefaultITMBaselineSystemPrompt

scenario_description_template:
  _target_: align_system.prompt_engineering.outlines_prompts.Phase2ScenarioDescriptionWCasualtyInfo
