name: pipeline_decision_flow

defaults:
  # Import defaults into this namspace (adm) as @name, for further
  # customization

  # Shared variables / components
  - /attribute@mu: medical_urgency
  - /attribute@af: affiliation_focus
  - /attribute@mf: merit_focus
  - /attribute@ss: search_or_stay
  - /attribute@ps: personal_safety
  - /inference_engine@structured_inference_engine: outlines_structured_greedy
  # ADM components to be used in "steps"
  - /adm_component/misc@step_definitions.format_choices: itm_format_choices
  - /adm_component/decision_flow@step_definitions.decision_flow: variable_extraction
  - /template/scenario_description@scenario_description_template: phase2
  - /template/prompt/decision_flow@prompt_template: variable_extraction
  - /template/output_schema/decision_flow@variable_extraction_output_schema: variable_extraction
  # Use definitions in this file to override defaults defined above
  - _self_

attribute_definitions:
  medical: ${adm.mu}
  affiliation: ${adm.af}
  merit: ${adm.mf}
  search: ${adm.ss}
  personal_safety: ${adm.ps}

step_definitions:
  decision_flow:
    scenario_description_template: ${ref:adm.scenario_description_template}
    prompt_template: ${ref:adm.prompt_template}
    output_schema_template: ${ref:adm.variable_extraction_output_schema}

instance:
  _target_: align_system.algorithms.pipeline_adm.PipelineADM

  steps:
    # Reference the step instances we want to use in order
    - ${ref:adm.step_definitions.format_choices}
    - ${ref:adm.step_definitions.decision_flow}
