defaults:
  - _single_kdma_aligned_base_IC

inference_kwargs:
  incontext:
    dataset: /data/shared/samba/integrated_results_metrics_eval/captured_dataset_for_chris/baseline_soartech_high-1716581856-input-output.json
