name: action_based

defaults:
  - interface: input_output_file
  - adm: single_kdma_baseline
  - override hydra/job_logging: custom

loglevel: "EXPLAIN"

save_log: true
save_input_output: true
save_scoring_output: true

align_to_target: False
