instance:
  _target_: align_system.algorithms.outlines_hybrid_regression_adm.HybridRegressionADM

  model_name: mistralai/Mistral-7B-Instruct-v0.2

inference_kwargs:
  models:
    model_name: 'bert-base-uncased'
    target_checkpoint:
      Moral judgement: /data/users/barry.ravichandran/ITM/attribute-alignment/checkpoints_full_train/moral_judgement/moral_judgement_bert-base-uncased_3e-05_2_16_epoch_16_test_acc_0.004499295485639288.pt
      Ingroup Bias: /data/users/barry.ravichandran/ITM/attribute-alignment/checkpoints_full_train/ingroup_bias/ingroup_bias_bert-base-uncased_3e-05_4_10_epoch_10_test_acc_0.012139826783467082.pt