instance:
  _target_: align_system.algorithms.outlines_hybrid_regression_adm.HybridRegressionADM

  model_name: mistralai/Mistral-7B-Instruct-v0.2

inference_kwargs:
  models:
    model_name: 'bert-base-uncased'
    target_checkpoint:
      Moral judgement: /data/shared/model_checkpoints/hybrid_regression/v2/moral_judgement.pt
      Ingroup Bias: /data/shared/model_checkpoints/hybrid_regression/v2/ingroup_bias.pt
      PerceivedQuantityOfLivesSaved: /data/shared/model_checkpoints/hybrid_regression/v2.2/value_of_life.pt
      QualityOfLife: /data/shared/model_checkpoints/hybrid_regression/v2.2/quality_of_life.pt
