instance:
  _target_: align_system.algorithms.hybrid_kaleido_adm.HybridKaleidoADM

  kaleido_adm:
    _target_: align_system.algorithms.kaleido_adm.KaleidoADM

    model_name: 'allenai/kaleido-large'
    use_tqdm: False

  outlines_adm:
    _target_: align_system.algorithms.outlines_adm.OutlinesTransformersADM

    model_name: mistralai/Mistral-7B-Instruct-v0.2
    baseline: true

inference_kwargs:
  # Kaleido kwargs
  distance_fn: 'RelevanceWeightedDistance'
  kdma_descriptions_map: 'align_system/algorithms/lib/templates/kdma_descriptions_short_metrics_eval.yml'
