instance:
  _target_: align_system.algorithms.oracle_adm.OracleADM

  probabilistic: false
  upweight_missing_kdmas: false
  filter_unlabeled_actions: false
  misaligned: false
  distribution_matching: sample
  kde_norm: globalnorm
