instance:
  _target_: align_system.algorithms.outlines_regression_adm.OutlinesTransformersRegressionADM

  model_name: mistralai/Mistral-7B-Instruct-v0.2
  baseline: false

inference_kwargs:
  num_samples: 10
  predict_outcomes: true
  distribution_matching: average
  generator_batch_size: 10