instance:
  _target_: align_system.algorithms.outlines_regression_adm_comparative.OutlinesTransformersComparativeRegressionADM

  model_name: mistralai/Mistral-7B-Instruct-v0.2
  baseline: false
  probabilistic: false

inference_kwargs:
  num_samples: 10
  predict_outcomes: true
  distribution_matching: sample
  kde_norm: globalnorm
  generator_batch_size: 5
  kdma_score_example: false
