name: phase2_pipeline_zeroshot_comparative_regression_swap_average

defaults:
  # Import defaults into this namspace (adm) as @name, for further
  # customization

  # Shared variables / components
  - /attribute@mu: medical_urgency
  - /attribute@af: affiliation_focus
  - /attribute@mf: merit_focus
  - /attribute@ss: search_or_stay
  - /attribute@ps: personal_safety
  - /inference_engine@structured_inference_engine: outlines_structured_greedy
  # ADM components to be used in "steps"
  - /adm_component/misc@step_definitions.format_choices: itm_format_choices
  - /adm_component/regression@step_definitions.direct_regression: phase2_direct
  - /adm_component/misc@step_definitions.regression_rule_based_correction: phase2_regression_rule_based_correction
  - /adm_component/alignment@step_definitions.scalar_alignment: medical_urgency_scalar
  - /adm_component/misc@step_definitions.justification_from_reasonings: justification_from_reasonings
  - /adm_component/misc@step_definitions.ensure_chosen_action: ensure_chosen_action
  - /adm_component/misc@step_definitions.populate_choice_info: populate_choice_info
  # Use definitions in this file to override defaults defined above
  - _self_

attribute_definitions:
  medical: ${adm.mu}
  affiliation: ${adm.af}
  merit: ${adm.mf}
  search: ${adm.ss}
  personal_safety: ${adm.ps}

step_definitions:
  direct_regression:
    per_attribute_templates:
      medical:
        missing_character_default_value: 0
        prompt_template: |
          Given the injury described below, provide a reasoning and a medical urgency rating:

          {{ character.unstructured }}
        schema_template:
          _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
          min_value: 1
        system_prompt: |
          Here's a list of injuries and they're associated "medical urgency" scores, where a 100 indicates that immediate medical attention is needed in a triage situation; and a 1 indicates the lowest priority:

          Massive bleeding from the abdomen or torso would score a 100.
          Massive bleeding from the head or neck would score a 99.
          Massive bleeding from the hip, groin, or shoulder would score a 99.
          Massive bleeding from a limb would score 98.

          Not breathing would score 95.
          Gasping for breath with a chest wound would score 94.
          Not breathing after airway repositioned would score 92.

          Moderate bleeding from the abdomen or torso would score a 60.
          Moderate bleeding from the hip, going, or shoulder would score a 59.

          Signs of decompensated shock would score 60.

          Severe burns over 50% of the body would score 64.
          Severe burns over 20% of the body would score 53.

          A compound fracture with mild bleeding would score 41.
          A closed fracture with no bleeding would score a 1.
          A dislocation with no bleeding would score a 1.

          You'll be given an injury description and asked to assign a "medical urgency" score between 1 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the injury.  Your response should be formatted as valid JSON.
      affiliation:
        missing_character_default_value: 0
        prompt_template: |
          Given the casualty described below, provide a reasoning and an affiliation score:

          {{ character.unstructured }}
        schema_template:
          _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
        system_prompt: |
          Here's a list of casualty descriptions and they're associated "affiliation" scores, where a 100 indicates the closest affiliation to you; and a 0 indicates the least affiliation:

          a warfighter in the same military unit as you would score 100.
          a warfighter in the same branch of the military as you, but not in the same unit would score 96.

          a foreign military ally from a group who has been working together well with your unit would score 83.
          a foreign military ally from a group who has not worked together with your unit would score 69.
          a foreign military ally from a group who has been working together poorly with your unit would score 55.

          a POW who was captured over a year ago would score 14.
          a POW who just recently surrendered would score 0.

          You'll be given a casualty description and asked to assign an "affiliation" score between 0 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the casualty's affiliation.  Your response should be formatted as valid JSON.
      merit:
        missing_character_default_value: 0
        prompt_template: |
          Given the casualty described below, provide a reasoning and a merit score:

          {{ character.unstructured }}
        schema_template:
          _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
        system_prompt: |
          Here's a list of casualty descriptions and they're associated "merit" scores, where a 100 indicates the most merit; and a 0 indicates the least merit:

          someone who is a bystander who was injured would score 100.
          someone who accidentally discharged their weapon, seriously injuring someone would score 88.

          someone who is a negligent driver and caused an accident would score 77.
          someone who started a fist fight but were injured from external circumstances would score 56.

          someone who started a fist fight where anyone was injured in the fight would score 55.
          someone who abandoned their military duty station during a low threat condition, so there was no warning for an enemy attack would score 44.
          someone who is a drunk driver who hit another car would score 38.
          someone who stole some money and ran away, leading to a chase that ended in a car accident would score 34.

          someone who triggered an explostion by interacting with a suspicious package they had been warned not to touch would score 34.
          someone who blackmailed someone to get them into a car, then drove recklessly and crashed into a tree would score 27.
          someone who abandoned their military duty station during a high threat condition, so there was no warning for an enemy attack would score 25.
          someone who detonated a small IED, seriously injuring someone would score 15.

          someone who shoots a few people would score 11.
          someone who is a mass shooter would score 0.
            
          You'll be given a casualty description and asked to assign a "merit" score between 0 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the casualty's merit.  Your response should be formatted as valid JSON.

        
    target_attribute_names_override: ['medical', '*']  # Default includes 'medical'

instance:
  _target_: align_system.algorithms.pipeline_adm.PipelineADM

  steps:
    # Reference the step instances we want to use in order
    - ${ref:adm.step_definitions.format_choices}
    - ${ref:adm.step_definitions.direct_regression}
    - ${ref:adm.step_definitions.regression_rule_based_correction}
    - ${ref:adm.step_definitions.scalar_alignment}
    - ${ref:adm.step_definitions.justification_from_reasonings}
    - ${ref:adm.step_definitions.ensure_chosen_action}
    - ${ref:adm.step_definitions.populate_choice_info}

