name: phase2_pipeline_zeroshot_comparative_regression_swap_average

defaults:
  # Import defaults into this namspace (adm) as @name, for further
  # customization

  # Shared variables / components
  - /attribute@mu: medical_urgency
  - /attribute@af: affiliation_focus
  - /attribute@mf: merit_focus
  - /attribute@ss: search_or_stay
  - /attribute@ps: personal_safety
  - /inference_engine@structured_inference_engine: outlines_structured_greedy
  - /template/scenario_description@scenario_description_template: phase2
  - /template/prompt@prompt_template: phase2_comparative_regression
  - /template/output_schema@comparative_regression_choice_schema: phase2_comparative_regression_choice
  # ADM components to be used in "steps"
  - /adm_component/misc@step_definitions.format_choices: itm_format_choices
  - /adm_component/icl@step_definitions.regression_icl: phase2_comparative
  - /adm_component/regression@step_definitions.direct_regression: phase2_direct
  - /adm_component/regression@step_definitions.comparative_regression: phase2_comparative_no_template
  - /adm_component/misc@step_definitions.regression_rule_based_correction: phase2_regression_rule_based_correction
  - /adm_component/alignment@step_definitions.scalar_alignment: medical_urgency_scalar
  - /adm_component/misc@step_definitions.justification_from_reasonings: justification_from_reasonings
  - /adm_component/misc@step_definitions.ensure_chosen_action: ensure_chosen_action
  - /adm_component/misc@step_definitions.populate_choice_info: populate_choice_info
  # Use definitions in this file to override defaults defined above
  - _self_

attribute_definitions:
  medical: ${adm.mu}
  affiliation: ${adm.af}
  merit: ${adm.mf}
  search: ${adm.ss}
  personal_safety: ${adm.ps}

step_definitions:
  regression_icl:
    scenario_description_template: ${ref:adm.scenario_description_template}
    attributes: ${adm.attribute_definitions}
    prompt_template: ${ref:adm.prompt_template}

  direct_regression:
    target_attribute_names_override: ['medical']  # Only medical here
    per_attribute_templates:
      medical:
        missing_character_default_value: 0
        prompt_template: |
          Given the injury described below, provide a reasoning and a medical urgency rating:

          {{ character.unstructured }}
        schema_template:
          _target_: align_system.prompt_engineering.outlines_prompts.DirectRegressionSchemaTemplate
          min_value: 1
        system_prompt: |
          Here's a list of injuries and they're associated "medical urgency" scores, where a 100 indicates that immediate medical attention is needed in a triage situation; and a 1 indicates the lowest priority:

          Massive bleeding from the abdomen or torso would score a 100.
          Massive bleeding from the head or neck would score a 99.
          Massive bleeding from the hip, groin, or shoulder would score a 99.
          Massive bleeding from a limb would score 98.

          Not breathing would score 95.
          Gasping for breath with a chest wound would score 94.
          Not breathing after airway repositioned would score 92.

          Moderate bleeding from the abdomen or torso would score a 60.
          Moderate bleeding from the hip, going, or shoulder would score a 59.

          Signs of decompensated shock would score 60.

          Severe burns over 50% of the body would score 64.
          Severe burns over 20% of the body would score 53.

          A compound fracture with mild bleeding would score 41.
          A closed fracture with no bleeding would score a 1.
          A dislocation with no bleeding would score a 1.

          You'll be given an injury description and asked to assign a "medical urgency" score between 1 to 100 along with a reasoning for your score.  Ignore any details that are not relevant to the injury.  Your response should be formatted as valid JSON.

  comparative_regression:
    scenario_description_template: ${ref:adm.scenario_description_template}
    prompt_template: ${ref:adm.prompt_template}
    score_schema_template: ${adm.comparative_regression_choice_schema}
    target_attribute_names_override: ['*']  # Default includes 'medical'
    output_conflict_resolver:
      _target_: align_system.algorithms.comparative_regression_adm_component.RegressionOutputsConflictResolver

instance:
  _target_: align_system.algorithms.pipeline_adm.PipelineADM

  steps:
    # Reference the step instances we want to use in order
    - ${ref:adm.step_definitions.format_choices}
    - ${ref:adm.step_definitions.regression_icl}
    - ${ref:adm.step_definitions.direct_regression}
    - ${ref:adm.step_definitions.comparative_regression}
    - ${ref:adm.step_definitions.regression_rule_based_correction}
    - ${ref:adm.step_definitions.scalar_alignment}
    - ${ref:adm.step_definitions.justification_from_reasonings}
    - ${ref:adm.step_definitions.ensure_chosen_action}
    - ${ref:adm.step_definitions.populate_choice_info}

