name: pipeline_comparative_regression

defaults:
  # Import defaults into this namspace (adm) as @name, for further
  # customization

  # Shared variables / components
  - /attribute@mj: moral_judgment
  - /attribute@ib: ingroup_bias
  - /attribute@qol: qol
  - /attribute@vol: vol
  - /inference_engine@structured_inference_engine: outlines_structured_inference_engine
  - /template/scenario_description@scenario_description_template: with_relevant_char_info
  - /template/prompt@prompt_template: comparative_regression
  - /template/output_schema@comparative_regression_choice_schema: comparative_regression_choice
  # ADM components to be used in "steps"
  - /adm_component/misc@step_definitions.format_choices: itm_format_choices
  - /adm_component/icl@step_definitions.regression_icl: regression
  - /adm_component/regression@step_definitions.comparative_regression: comparative
  - /adm_component/alignment@step_definitions.scalar_alignment: avg_dist_scalar
  - /adm_component/misc@step_definitions.justification_from_reasonings: justification_from_reasonings
  - /adm_component/misc@step_definitions.action_parameter_completion: action_parameter_completion
  - /adm_component/misc@step_definitions.ensure_chosen_action: ensure_chosen_action
  # Use definitions in this file to override defaults defined above
  - _self_

attribute_definitions:
  Moral judgement: ${adm.mj}
  Ingroup Bias: ${adm.ib}
  QualityOfLife: ${adm.qol}
  PerceivedQuantityOfLivesSaved: ${adm.vol}

step_definitions:
  regression_icl:
    scenario_description_template: ${ref:adm.scenario_description_template}
    attributes: ${adm.attribute_definitions}
    prompt_template: ${ref:adm.prompt_template}
    icl_generator:
      target_kdmas:
        - ${adm.mj}

  comparative_regression:
    scenario_description_template: ${ref:adm.scenario_description_template}
    prompt_template: ${ref:adm.prompt_template}
    score_schema_template: ${adm.comparative_regression_choice_schema}

instance:
  _target_: align_system.algorithms.pipeline_adm.PipelineADM

  steps:
    # Reference the step instances we want to use in order
    - ${ref:adm.step_definitions.format_choices}
    - ${ref:adm.step_definitions.regression_icl}
    - ${ref:adm.step_definitions.comparative_regression}
    - ${ref:adm.step_definitions.scalar_alignment}
    - ${ref:adm.step_definitions.justification_from_reasonings}
    - ${ref:adm.step_definitions.action_parameter_completion}
    - ${ref:adm.step_definitions.ensure_chosen_action}
