name: pipeline

defaults:
  - /attribute@mj: moral_judgment
  - /inference_engine@structured_inference_engine: outlines_structured_inference_engine
  - /template/scenario_description@scenario_description_template: default
  - /template/prompt@prompt_template: comparative_regression
  - /template/output_schema@comparative_regression_choice_schema: comparative_regression_choice
  - /adm_component/icl@instance.steps.0: regression
  - /adm_component/regression@instance.steps.1: comparative
  - /adm_component/alignment@instance.steps.2: avg_dist_scalar
  - /adm_component/misc@instance.steps.3: action_parameter_completion
  - _self_

attribute_definitions:
  Moral judgement: ${adm.mj}

instance:
  _target_: align_system.algorithms.pipeline_adm.PipelineADM

  steps:
    "0":
      scenario_description_template: ${ref:adm.scenario_description_template}
      attributes: ${adm.attribute_definitions}
      prompt_template: ${ref:adm.prompt_template}
      icl_generator:
        target_kdmas:
          - ${adm.mj}
    "1":
      scenario_description_template: ${ref:adm.scenario_description_template}
      prompt_template: ${ref:adm.prompt_template}
      score_schema_template: ${adm.comparative_regression_choice_schema}
