name: pipeline_relevance

defaults:
  # Import defaults into this namspace (adm) as @name, for further
  # customization

  # Shared variables / components
  - /attribute@mj: moral_judgment
  - /inference_engine@structured_inference_engine: outlines_structured_inference_engine
  - /template/scenario_description@scenario_description_template: default
  - /template/prompt@relevance_prompt_template: relevance_classification
  - /template/output_schema@relevance_classification_schema: relevance_classification_choice
  - /template/prompt@prompt_template: comparative_regression
  - /template/output_schema@comparative_regression_choice_schema: comparative_regression_choice
  # ADM components to be used in "steps"
  - /adm_component/icl@step_definitions.relevance_icl: choice_relevance
  - /adm_component/relevance@step_definitions.relevance_classification: choice_classification
  - /adm_component/icl@step_definitions.regression_icl: regression
  - /adm_component/regression@step_definitions.comparative_regression: comparative
  - /adm_component/alignment@step_definitions.scalar_alignment: avg_dist_scalar
  - /adm_component/misc@step_definitions.action_parameter_completion: action_parameter_completion
  # Use definitions in this file to override defaults defined above
  - _self_

attribute_definitions:
  Moral judgement: ${adm.mj}

step_definitions:
  relevance_icl:
    scenario_description_template: ${ref:adm.scenario_description_template}
    attributes: ${adm.attribute_definitions}
    prompt_template: ${ref:adm.relevance_prompt_template}
    icl_generator:
      target_kdmas:
        - ${adm.mj}

  relevance_classification:
    scenario_description_template: ${ref:adm.scenario_description_template}
    prompt_template: ${ref:adm.relevance_prompt_template}
    score_schema_template: ${adm.relevance_classification_schema}

  regression_icl:
    scenario_description_template: ${ref:adm.scenario_description_template}
    attributes: ${adm.attribute_definitions}
    prompt_template: ${ref:adm.prompt_template}
    icl_generator:
      target_kdmas:
        - ${adm.mj}

  comparative_regression:
    scenario_description_template: ${ref:adm.scenario_description_template}
    prompt_template: ${ref:adm.prompt_template}
    score_schema_template: ${adm.comparative_regression_choice_schema}

instance:
  _target_: align_system.algorithms.pipeline_adm.PipelineADM

  steps:
    # Reference the step instances we want to use in order
    - ${ref:adm.step_definitions.relevance_icl}
    - ${ref:adm.step_definitions.relevance_classification}
    - ${ref:adm.step_definitions.regression_icl}
    - ${ref:adm.step_definitions.comparative_regression}
    - ${ref:adm.step_definitions.scalar_alignment}
    - ${ref:adm.step_definitions.action_parameter_completion}
