name: pipeline

defaults:
  - /attribute@mj: moral_judgment
  - /adm_component/icl@instance.steps.0: regression
  - /adm_component/regression@instance.steps.1: comparative
  - /adm_component/alignment@instance.steps.2: avg_dist_scalar
  - _self_

attribute_definitions:
  Moral judgement: ${adm.mj}

scenario_description_template:
  _target_: align_system.prompt_engineering.outlines_prompts.ScenarioDescriptionWithRelevantCharInfo

  relevant_structured_char_info_lookup:
    moral judgment: ['intent', 'directness_of_causality', 'injuries']
    ingroup bias: ['all_unique']
    quality of life: ['demographics.age', 'injuries', 'vitals']
    perceived quantity of lives saved: []

prompt_template:
  _target_: align_system.prompt_engineering.outlines_prompts.ComparativeKDMAScorePredictionPromptNoOutcomes

comparative_regression_choice_schema:
  _target_: align_system.prompt_engineering.outlines_prompts.ComparativeKDMAScorePredictionSchema

  factor_lookup:
    moral judgment: 100
    ingroup bias: 100
    quality of life: 10
    perceived quantity of lives saved: 10

instance:
  _target_: align_system.algorithms.pipeline_adm.PipelineADM

  steps:
    "0":
      scenario_description_template: ${adm.scenario_description_template}
      attributes: ${adm.attribute_definitions}
      prompt_template: ${adm.prompt_template}
      icl_generator:
        target_kdmas:
          - ${adm.mj}
    "1":
      scenario_description_template: ${adm.scenario_description_template}
      prompt_template: ${adm.prompt_template}
      score_schema_template: ${adm.comparative_regression_choice_schema}
