instance:
  _target_: align_system.algorithms.relevance_outlines_regression_adm_comparative.OutlinesTransformersComparativeRegressionRelevanceADM

  model_name: mistralai/Mistral-7B-Instruct-v0.2
  baseline: false
  probabilistic: false

inference_kwargs:
  num_samples: 10
  predict_outcomes: false
  distribution_matching: relevance_average
  generator_batch_size: 5
  kdma_score_example: true
