id: Jun2026-SS-8
kdma_values:
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.896427
    type: single
  - name: attr_weight
    value: -1.64847
    type: single
  - name: medical_weight
    value: -0.80995
    type: single
