id: Jun2026-SS-6
kdma_values:
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.0
    type: single
  - name: attr_weight
    value: -0.8
    type: single
  - name: medical_weight
    value: -1.0
    type: single
