id: Jun2026-AF-binomial-4
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.6
    type: single
  - name: attr_weight
    value: 3.0
    type: single
  - name: medical_weight
    value: 0.4
    type: single
