id: Jun2026-AF6-SS4
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.4
    type: single
  - name: attr_weight
    value: 0.5
    type: single
  - name: medical_weight
    value: 0.4
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.5
    type: single
  - name: attr_weight
    value: -0.4
    type: single
  - name: medical_weight
    value: -0.9
    type: single
