id: Jun2026-AF3-SS3
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.66656
    type: single
  - name: attr_weight
    value: -0.31016
    type: single
  - name: medical_weight
    value: 1.354145
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.239205
    type: single
  - name: attr_weight
    value: -1.13703
    type: single
  - name: medical_weight
    value: -1.18027
    type: single
