id: Jun2026-PS-trinomial-7
kdma_values:
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.2
    type: single
  - name: attr_weight
    value: 1.1
    type: single
  - name: medical_weight
    value: 1.3
    type: single
