id: Jun2026-AF1-SS7
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.75168
    type: single
  - name: attr_weight
    value: 0.261026
    type: single
  - name: medical_weight
    value: 3.579457
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.364983
    type: single
  - name: attr_weight
    value: -1.30751
    type: single
  - name: medical_weight
    value: -1.5506
    type: single
