id: Jun2026-AF7-SS4
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.49632
    type: single
  - name: attr_weight
    value: 0.032553
    type: single
  - name: medical_weight
    value: 2.837686
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.77065
    type: single
  - name: attr_weight
    value: -0.6256
    type: single
  - name: medical_weight
    value: -0.62479
    type: single
