id: Jun2026-SS-1
kdma_values:
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.8
    type: single
  - name: attr_weight
    value: -2.0
    type: single
  - name: medical_weight
    value: -1.2
    type: single
