id: Jun2026-MF-5
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.4
    type: single
  - name: attr_weight
    value: 0.4
    type: single
  - name: medical_weight
    value: 3.7
    type: single
