id: Jun2026-AF4-SS8
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.6
    type: single
  - name: attr_weight
    value: 0.4
    type: single
  - name: medical_weight
    value: 3.0
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.2
    type: single
  - name: attr_weight
    value: -1.3
    type: single
  - name: medical_weight
    value: -1.7
    type: single
