id: Jun2026-SS-5
kdma_values:
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.9
    type: single
  - name: attr_weight
    value: -1.4
    type: single
  - name: medical_weight
    value: -0.7
    type: single
