id: Jun2026-AF7-SS7
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.3
    type: single
  - name: attr_weight
    value: -0.4
    type: single
  - name: medical_weight
    value: -0.1
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 1.7
    type: single
  - name: attr_weight
    value: -0.7
    type: single
  - name: medical_weight
    value: -1.3
    type: single
