id: Jun2026-AF4-SS4
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.624
    type: single
  - name: attr_weight
    value: -0.19592
    type: single
  - name: medical_weight
    value: 2.466801
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.77065
    type: single
  - name: attr_weight
    value: -0.6256
    type: single
  - name: medical_weight
    value: -0.62479
    type: single
