id: Jun2026-AF6-SS4
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.53888
    type: single
  - name: attr_weight
    value: -0.08168
    type: single
  - name: medical_weight
    value: 1.72503
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.77065
    type: single
  - name: attr_weight
    value: -0.6256
    type: single
  - name: medical_weight
    value: -0.62479
    type: single
