id: Jun2026-AF-7
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.49632
    type: single
  - name: attr_weight
    value: 0.032553
    type: single
  - name: medical_weight
    value: 2.837686
    type: single
