id: Jun2026-PS-binomial-2
kdma_values:
- kdma: personal_safety
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -1.25
    type: single
  - name: attr_weight
    value: 1.0
    type: single
  - name: medical_weight
    value: 0.3
    type: single
