id: Jun2026-AF2-SS3
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.7
    type: single
  - name: attr_weight
    value: 1.6
    type: single
  - name: medical_weight
    value: 0.7
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.2
    type: single
  - name: attr_weight
    value: -1.1
    type: single
  - name: medical_weight
    value: -1.1
    type: single
