id: Jun2026-MF-1
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.290547
    type: single
  - name: attr_weight
    value: 1.055877
    type: single
  - name: medical_weight
    value: 4.533242
    type: single
