id: Jun2026-MF-2
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.464552
    type: single
  - name: attr_weight
    value: 1.204177
    type: single
  - name: medical_weight
    value: 0.803047
    type: single
