id: Jun2026-AF5-SS7
kdma_values:
- kdma: affiliation
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: -0.58144
    type: single
  - name: attr_weight
    value: 0.14679
    type: single
  - name: medical_weight
    value: 2.095916
    type: single
- kdma: search
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 2.364983
    type: single
  - name: attr_weight
    value: -1.30751
    type: single
  - name: medical_weight
    value: -1.5506
    type: single
