id: Jun2026-MF-7
kdma_values:
- kdma: merit
  value: null
  kdes: null
  parameters:
  - name: intercept
    value: 0.7
    type: single
  - name: attr_weight
    value: 1.1
    type: single
  - name: medical_weight
    value: 1.0
    type: single
