adm:
  name: 'KaleidoADM'
  init_kwargs:
    model_name: 'allenai/kaleido-large'
    use_tqdm: False

  inference_kwargs:
    distance_fn: 'RelevanceWeightedDistance'
    kdma_descriptions_map: 'align_system/algorithms/lib/templates/kdma_descriptions_short_metrics_eval.yml'
