adm:
  name: 'PersonaADM'
  init_kwargs:
    root_model: google/gemma-2-9b
    generation_kwargs:
      do_sample: true
      temperature: 0.7
      top_k: 50
      top_p: 0.95
      max_new_tokens: 512

alignment_target_override:
  id: ADEPT-metrics_eval-alignment-target-train-HIGH
  kdma_values:
    - {kdma: MoralDesert, value: 1}
