adm:
  name: 'SingleKDMAADM'
  init_kwargs:
    hf_model: meta-llama/Llama-2-13b-chat-hf
    precision: half
    temperature: 0.7

  inference_kwargs:
    baseline: false
    n_negative_samples: 0
    n_positive_samples: 1
    shuffle: true
