adm:
  name: 'SingleKDMAADM'
  init_kwargs:
    hf_model: meta-llama/Llama-2-7b-chat-hf
    precision: half
    temperature: 0.7

  inference_kwargs:
    baseline: false
    n_negative_samples: 0
    n_positive_samples: 1
    shuffle: true

alignment_target_override:
  id: ADEPT-metrics_eval-alignment-target-train-LOW
  kdma_values:
    - {kdma: MoralDesert, value: 0}
