_target_: align_system.data_models.compat.ta3_ph1_client_models.AlignmentTarget
id: vol-synth-HighCluster-ph1
kdma_values:
- kdes:
    globalnorm:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMAAAAAAAAPA/

        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEAAAAAAAAPA/

        AAAAAAAA8D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: globalnorm
    globalnormx_localnormy:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwKMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwKGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDYAAAAAAAAPA/

        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A

        AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RSlChLAUsGhZRo

        J4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEAAAAAAAAAAgAA

        AAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeM

        A1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFk

        aXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsI

        hpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAABAAAAAAAAAAAA

        AAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsCh5RoKolDIAAAAAAAAPA/AAAAAAAA8D8A

        AAAAAADwPwAAAAAAAPA/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: globalnormx_localnormy
    localnorm:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMAAAAAAAAPA/

        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEAAAAAAAAPA/

        AAAAAAAA8D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: localnorm
    rawscores:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMM3MzMzMzOw/

        zczMzMzM7D/NzMzMzMzsP83MzMzMzOw/zczMzMzM7D/NzMzMzMzsP5R0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEM3MzMzMzOw/

        zczMzMzM7D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: rawscores
  kdma: QualityOfLife
  scores:
  - 0.9
  - 0.9
  - 0.9
  - 0.9
  - 0.9
  - 0.9
- kdes:
    globalnorm:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMP///////+c/

        ////////5z8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAAIAAAAAAMA/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEP///////+c/

        AAAAAAAA8D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: globalnorm
    globalnormx_localnormy:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwKMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwKGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDYP///////+c/

        ////////5z/////////nP////////+c/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A

        AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RSlChLAUsGhZRo

        J4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEAAAAAAAAAAgAA

        AAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeM

        A1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFk

        aXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsI

        hpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAABAAAAAAAAAM87

        f2aeoMY/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsCh5RoKolDIP///////+c/////////5z8A

        AAAAAADwPwAAAAAAAPA/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: globalnormx_localnormy
    localnorm:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMP///////+c/

        ////////5z8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAAIAAAAAAMA/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEP///////+c/

        AAAAAAAA8D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: localnorm
    rawscores:
      kde: 'gASVJAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsGSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDMGZmZmZmZuY/

        ZmZmZmZm5j/NzMzMzMzsP83MzMzMzOw/zczMzMzM7D/NzMzMzMzsP5R0lGJoHWggSwCFlGgih5RS

        lChLAUsGhZRoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQzAAAAAAAAAAAAEA

        AAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19s

        ZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJL

        AIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAABgAAAAAAAAAB

        AAAAAAAAAJyZmZmZmbk/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEGZmZmZmZuY/

        zczMzMzM7D+UdJRiSyhLAUsBSwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNz

        lGgVk5RoWIwTRXVjbGlkZWFuRGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RS

        lChLAUsBhZRoKolDCAAAAAAAAAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAA

        AAAAAJR0lGKHlGJOdJRijBBfc2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: rawscores
  kdma: PerceivedQuantityOfLivesSaved
  scores:
  - 0.7
  - 0.7
  - 0.9
  - 0.9
  - 0.9
  - 0.9
